linux_compiler_flags = [
  '-lpthread',
]

cxx_binary(
  name = 'test',
  header_namespace = '',
  headers = subdir_glob([
    ('c', '**/*.hpp'),
    ('c', '**/*.h'),
  ]) ,
  srcs = glob([
    'c/**/*.cpp',
  ]),
  platform_compiler_flags = [
    ('default', linux_compiler_flags),
    ('^linux.*', linux_compiler_flags),
  ],
  deps = [
    '//:internal',
    '//:seasocks',
  ],
)
